(import (rnrs base)
        (aoc matrix)
        (test csv)
        (aoc file)
        (aoc data))
(define (get-data filename)
  (let ((data (filename->char-lines filename)))
    (list->matrix (map (lambda (char-line)
                         (map list->string->num (map list char-line))) data))))

(define data (get-data "../data/test_matrix.dat"))
(test-start)
(test-assert "item access" (and (= (matrix-element data 0 0) 1)
                                (= (matrix-element data 0 1) 2)
                                (= (matrix-element data 0 2) 3)
                                (= (matrix-element data 1 0) 4)
                                (= (matrix-element data 1 1) 5)
                                (= (matrix-element data 1 2) 6)
                                (= (matrix-element data 2 0) 7)
                                (= (matrix-element data 2 1) 8)
                                (= (matrix-element data 2 2) 9)))
(test-assert "row access" (and (equal? (matrix-row data 0) '#(1 2 3))
                               (equal? (matrix-row data 1) '#(4 5 6))
                               (equal? (matrix-row data 2) '#(7 8 9))))

(test-assert "column access" (and (equal? (matrix-column data 0) '#(1 4 7))
                                  (equal? (matrix-column data 1) '#(2 5 8))
                                  (equal? (matrix-column data 2) '#(3 6 9))))
(let* ((first #f)
       (last #f)
       (map-f (lambda (element i j)
                (cond
                  ((= element 1) (set! first (list i j))
                                 (* element element))
                  ((= element 9) (set! last (list i j))
                                 (* element element))
                  (else (* element element)))))
       (squares (matrix-map map-f data)))
  (test-equal "start set value" first '(0 0))
  (test-equal "end set value" last '(2 2))
  (test-assert "matrix-map" (and (= (matrix-element squares 0 0) 1)
                                (= (matrix-element squares 0 1) 4)
                                (= (matrix-element squares 0 2) 9)
                                (= (matrix-element squares 1 0) 16)
                                (= (matrix-element squares 1 1) 25)
                                (= (matrix-element squares 1 2) 36)
                                (= (matrix-element squares 2 0) 49)
                                (= (matrix-element squares 2 1) 64)
                                (= (matrix-element squares 2 2) 81))))
(test-assert "item access 2" (and (= (matrix-element data 0 0) 1)
                                (= (matrix-element data 0 1) 2)
                                (= (matrix-element data 0 2) 3)
                                (= (matrix-element data 1 0) 4)
                                (= (matrix-element data 1 1) 5)
                                (= (matrix-element data 1 2) 6)
                                (= (matrix-element data 2 0) 7)
                                (= (matrix-element data 2 1) 8)
                                (= (matrix-element data 2 2) 9)))
(test-equal "vector transpose" '#(#(1 4 7) #(2 5 8) #(3 6 9)) (vector-transpose (matrix-rows data)))
(test-equal "sub matrix" '#(#(2 3) #(5 6)) (matrix-rows (keep-for-submatrix data '(0 1) '(1 2))))
(test-end)
