(import (rnrs)
        (prefix (day day01) day01-)
        (prefix (day day02) day02-)
        (prefix (day day03) day03-)
        (prefix (day day04) day04-)
        (test csv))
(test-start)
;;day 1 tests
(let ((data (day01-get-data "../data/day01-example1.dat")))
  (test-equal "ends on zero" 3 (day01-count-zeros data))
  (test-equal "passes zero" 6 (day01-count-zero-passes data))
  (test-assert "forum edge cases" (and (= 2 (day01-count-zero-passes '(("L" 150) ("L" 50))))
                                       (= 2 (day01-count-zero-passes '(("L" 150) ("R" 50))))
                                       (= 2 (day01-count-zero-passes '(("R" 150) ("L" 50))))
                                       (= 2 (day01-count-zero-passes '(("R" 150) ("R" 50))))
                                       )))
;;day 2 tests
(let ((data (day02-get-data "../data/day02-example1.dat")))
  (test-equal "doubles invalid" 1227775554 (fold-left + 0 (day02-invalid-ids-numeric data)))
  (test-equal "all n-tuples invalid" 4174379265 (fold-left + 0 (day02-invalid-all-reps data))))
;;day 3 tests
(let ((data (day03-get-data "../data/day03-example1.dat")))
  (test-equal "total joltage" 357 (day03-total-output data))
  (test-equal "override joltage (12 banks)" 3121910778619 (day03-total-overide-output data)))
;; day 4 tests
(let ((data (day04-get-data "../data/day04-example1.dat")))
  (test-equal "4.1 rolls less than 4" 13 (day04-count-accessible data 4))
  (test-equal "4.2 rools less than 4 with removal" 43 (day04-count-all-accessible data 4)))
(test-end)

#;(let ((data (day04-get-data "../data/day04-input.dat")))
  (display (day04-count-accessible data 4))
  (newline)
  (display (day04-count-all-accessible data 4))
  (newline))

#;(let ((data (day03-get-data "../data/day03-input.dat")))
  (display (day03-total-output data))
  (newline)
  (display (day03-total-overide-output data))
  (newline))
  
#;(let ((data (day02-get-data "../data/day02-input.dat")))
  (display (fold-left + 0 (day02-invalid-ids-numeric data)))
  (newline)
  (display (fold-left + 0 (day02-invalid-all-reps data)))
  (newline))
