(import (rnrs)
        (prefix (day day01) day01-)
        (prefix (day day02) day02-)
        (test csv))
(test-start)
;;day 1 tests
(let ((data (day01-get-data "../data/day01-example1.dat")))
  (test-equal "ends on zero" 3 (day01-count-zeros data))
  (test-equal "passes zero" 6 (day01-count-zero-passes data))
  (test-assert "forum edge cases" (and (= 2 (day01-count-zero-passes '(("L" 150) ("L" 50))))
                                       (= 2 (day01-count-zero-passes '(("L" 150) ("R" 50))))
                                       (= 2 (day01-count-zero-passes '(("R" 150) ("L" 50))))
                                       (= 2 (day01-count-zero-passes '(("R" 150) ("R" 50))))
                                       )))
;;day 2 tests
(let ((data (day02-get-data "../data/day02-example1.dat")))
  (test-equal "doubles invalid" 1227775554 (fold-left + 0 (day02-invalid-ids-numeric data)))
  (test-equal "all n-tuples invalid" 4174379265 (fold-left + 0 (day02-invalid-all-reps data))))
(test-end)

#;(let ((data (day02-get-data "../data/day02-input.dat")))
  (display (fold-left + 0 (day02-invalid-ids-numeric data)))
  (newline)
  (display (fold-left + 0 (day02-invalid-all-reps data)))
  (newline))
