(import (rnrs)
        (prefix (day day01) day01-)
        (prefix (day day02) day02-)
        (prefix (day day03) day03-)
        (prefix (day day04) day04-)
        (prefix (day day05) day05-)
        (prefix (day day06) day06-)
        (test csv))
(test-start)
;;day 1 tests
(let ((data (day01-get-data "../data/day01-example1.dat")))
  (test-equal "1.1 ends on zero" 3 (day01-count-zeros data))
  (test-equal "1.2 passes zero" 6 (day01-count-zero-passes data))
  (test-assert "1.2 forum edge cases" (and (= 2 (day01-count-zero-passes '(("L" 150) ("L" 50))))
                                       (= 2 (day01-count-zero-passes '(("L" 150) ("R" 50))))
                                       (= 2 (day01-count-zero-passes '(("R" 150) ("L" 50))))
                                       (= 2 (day01-count-zero-passes '(("R" 150) ("R" 50))))
                                       )))
;;day 2 tests
(let ((data (day02-get-data "../data/day02-example1.dat")))
  (test-equal "2.1 doubles invalid" 1227775554 (fold-left + 0 (day02-invalid-ids-numeric data)))
  (test-equal "2.1 all n-tuples invalid" 4174379265 (fold-left + 0 (day02-invalid-all-reps data))))
;;day 3 tests
(let ((data (day03-get-data "../data/day03-example1.dat")))
  (test-equal "3.1 total joltage" 357 (day03-total-output data))
  (test-equal "3.2 override joltage (12 banks)" 3121910778619 (day03-total-overide-output data)))
;; day 4 tests
(let ((data (day04-get-data "../data/day04-example1.dat")))
  (test-equal "4.1 rolls less than 4" 13 (day04-count-accessible data 4))
  (test-equal "4.2 rools less than 4 with removal" 43 (day04-count-all-accessible data 4)))
;; day 5 tests
(let ((data (day05-get-data "../data/day05-example1.dat")))
  (test-equal "5.1 fresh in range" 3 (day05-count-fresh data))
  (test-equal "5.2 all in ranges" 14 (day05-count-all-fresh data))
  (test-equal "5.2 forum edge case" 16 (day05-count-all-fresh (day05-get-data "../data/day05-example2.dat"))))
;; day 6 tests
(let ((data (day06-get-data "../data/day06-example1.dat"))
      (data-2 (day06-get-data-2 "../data/day06-example1.dat")))
  (test-equal "6.1 sum all problems" 4277556 (day06-problem-sum data))
  (test-equal "6.2 sum with vertical numbers" 3263827 (day06-problem-sum data-2)))
(test-end)

(let ((data (day06-get-data "../data/day06-input.dat")))
  (display (day06-problem-sum data))
  (newline)
  (display (day06-problem-sum (day06-get-data-2 "../data/day06-input.dat")))
  (newline))
#;(let ((data (day05-get-data "../data/day05-input.dat")))
  (display (day05-count-fresh data))
  (newline)
  (display (day05-count-all-fresh data))
  (newline))

#;(let ((data (day04-get-data "../data/day04-input.dat")))
  (display (day04-count-accessible data 4))
  (newline)
  (display (day04-count-all-accessible data 4))
  (newline))

#;(let ((data (day03-get-data "../data/day03-input.dat")))
  (display (day03-total-output data))
  (newline)
  (display (day03-total-overide-output data))
  (newline))
  
#;(let ((data (day02-get-data "../data/day02-input.dat")))
  (display (fold-left + 0 (day02-invalid-ids-numeric data)))
  (newline)
  (display (fold-left + 0 (day02-invalid-all-reps data)))
  (newline))
